# 异步函数

- ES8 新增异步函数（`async/await`），是 ES6 期约模式在 ECMAScript 函数中的应用
- 以**同步方式的代码执行异步**

<a href="" target="_blank">相关代码 →</a>

## 异步函数

- ES8 对函数进行了扩展，新增 2 个关键字`async`和`await`

### async

- `async`关键字用于声明异步函数，可用在**函数声明**、**函数表达式**、**箭头函数**和**方法**上

```js
async function foo() {} // 用在函数声明
let bar = async function () {} // 用在函数表达式
let baz = async () => {} // 用在箭头函数
class Qux {
  async qux() {} // 用在方法
}
```

- `async`关键字让函数具有**异步特性**，代码仍**同步求值**，参数或闭包也具有普通 JS 函数的正常行为

```js
async function foo() {
  console.log(1)
}
foo()
console.log(2)
/* 
  1，foo()函数先被求值
  2
*/
```

- 异步函数`return`返回的值，会被`Promise.resolve()`包装成期约对象，调用异步函数**始终返回该期约对象**
  - 若`return`关键字返回的是实现`thenable`接口的对象（`callback`、期约），该对象由提供给`then()`的处理程序**解包**
  - 若`return`关键字返回的是常规的值，返回值被当作**已解决的期约**（无`return`关键字，返回值被当作 undefined）

```js
async function foo() {
  return 'foo' // 返回原始值
}
console.log(foo()) // Promise {<fulfilled>: "foo"}，被当作已解决的期约
foo().then((result) => console.log(result)) // 'foo'

async function bar2() {
  return ['bar'] // 返回没有实现thenable接口的对象
}
console.log(bar2()) // Promise {<fulfilled>: ['bar']}，被当作已解决的期约
bar2().then((result) => console.log(result)) // ['bar']

async function baz2() {
  const thenable = {
    then(callback) {
      callback('baz')
    },
  }
  return thenable // 返回实现了thenable接口的非期约对象
}
console.log(baz2()) // Promise {<pending>}
baz2().then((result) => console.log(result)) // 'baz'，由then()解包

async function qux() {
  return Promise.resolve('qux') // 返回解决的期约
}
console.log(qux()) // Promise {<pending>}
qux().then((result) => console.log(result)) // 'qux'，由then()解包

async function rejectQux() {
  return Promise.reject('qux') // 返回拒绝的期约
}
console.log(rejectQux()) // Promise {<pending>}
rejectQux().then(null, (result) => console.log(result)) // 'qux'，由then()解包
// Uncaught (in promise) qux
rejectQux().catch((result) => console.log(result)) // 'qux'，由catch()解包
```

- 异步函数中**抛出错误**会返回**拒绝的期约**

```js
async function foo() {
  console.log(1)
  throw 3
}
foo().catch((result) => console.log(result)) // 给返回的期约添加拒绝处理程序
console.log(2)
/* 
  1，foo()函数先被求值
  2
  3
*/
```

- 异步函数中**拒绝期约的错误（非“返回拒绝的期约”）**不会被异步函数捕获

```js
async function foo() {
  Promise.reject(3) // 拒绝的期约（非返回）
}
foo().catch((result) => console.log(result)) // catch()方法捕获不到
// Uncaught (in promise) 3，浏览器消息队列捕获
```

### await

- 使用`await`关键字可以**暂停**异步函数代码执行，**等待期约解决**

```js
let p = new Promise((resolve, reject) => {
  setTimeout(resolve, 1000, 3)
})
p.then((x) => console.log(x)) // 3

// 用async/await重写
async function foo() {
  let p = new Promise((resolve, reject) => {
    setTimeout(resolve, 1000, 3)
  })
  console.log(await p)
}
foo() // 3
```

- `await`会尝试**解包**对象的值（与`yield`类似），然后将该值传给表达式，而后异步恢复执行异步函数

```js
async function foo() {
  console.log(await Promise.resolve('foo')) // 将期约解包，再将值传给表达式
}
foo()

async function bar2() {
  return await Promise.resolve('bar')
}
bar2().then((res) => console.log(res)) // 'bar'

async function baz2() {
  await new Promise((resolve, reject) => {
    setTimeout(resolve, 1000)
  })
  console.log('baz')
}
baz2() // 'baz'（1000毫秒后）
```

- `await`根据等待的值，执行不同的操作
  - 若等待的值是实现`thenable`接口的对象（`callback`、期约），该对象由`await`来**解包**
  - 若等待的值是常规值，该值被当作**已解决的期约**（然后再由`await`来解包）

```js
async function foo() {
  console.log(await 'foo') // 等待原始值，被当作已解决的期约Promise.resolve('foo')，再由await解包
}
foo() // 'foo'

async function bar2() {
  console.log(await ['bar']) // 等待值是没有实现thenable接口的对象，被当作已解决的期约再由await解包
}
bar2() // ["bar"]

async function baz2() {
  const thenable = {
    then(callback) {
      callback('baz')
    },
  }
  console.log(await thenable) // 等待值是实现了thenable接口的非期约对象，由await解包
}
baz2() // 'baz'

async function qux() {
  console.log(await Promise.resolve('qux')) // 等待值是解决的期约
}
qux() // 'qux'
```

- 等待会**抛出错误**的同步操作，会返回**拒绝的期约**

```js
async function foo() {
  console.log(1)
  await (() => {
    throw 3 // 抛出错误的同步操作
  })()
}
foo().catch((result) => console.log(result)) // 给返回的期约添加拒绝处理程序
console.log(2)
/* 
  1
  2
  3
*/
```

- 对**拒绝的期约**使用`await`，会**释放**错误值（将拒绝期约返回）

```js
async function foo() {
  console.log(1)
  await Promise.reject(3) // 对拒绝的期约使用await，将其返回（后续代码不再执行）
  console.log(4) // 不执行
}
foo().catch((result) => console.log(result)) // 给返回的期约添加拒绝处理程序
console.log(2)
/* 
  1
  2
  3
*/
```

### await 的限制

- **必须**在**异步函数**中使用
- **不能**在顶级上下文（如`<script>`标签或模块）中使用
- 可以**定义并立即调用**异步函数
- 异步函数的特质**不会扩展到嵌套函数**

```js
async function foo() {
  console.log(await Promise.resolve(3)) // 必须在异步函数中使用
}
foo() // 3
;(async function () {
  console.log(await Promise.resolve(3)) // 3，立即调用的异步函数表达式
})()

const syncFn = async () => {
  console.log(await Promise.resolve(3)) // 在箭头函数中使用，箭头函数前一样要加async
}
syncFn() // 3

function foo() {
  // console.log(await Promise.resolve(3)) // 不允许在同步函数中使用
}

async function foo() {
  // function bar() {
  //   console.log(await Promise.resolve(3)) // 错误：异步函数不会扩展到嵌套函数
  // }
  async function bar() {
    console.log(await Promise.resolve(3)) // 需要在bar前加async
  }
}
```

## 停止和恢复执行

- `async/await`真正起作用的是`await`（`async`只是标识符）
  - JS 在运行时碰到`await`关键字，会**记录**在哪里暂停执行
  - 等到`await`**右边的值可以用**时，JS 向消息队列推送任务，该任务**恢复异步函数的执行**
  - 即使`await`右边跟着一个立即可用的值，函数也会暂停，且其余部分会被**异步求值**

```js
// async只是标识符
async function foo() {
  console.log(2)
}
console.log(1)
foo()
console.log(3)
/* 
  1
  2
  3
*/

// 遇到await -> 记录暂停 -> await右边的值可用 -> 恢复执行异步函数
async function foo() {
  console.log(2)
  await null // 暂停，且后续操作变为异步
  // 为立即可用的值null向消息队列中添加一个任务
  console.log(4)
}
console.log(1)
foo()
console.log(3)
/* 
  1
  2
  3
  4
*/
```

- 如果`await`后面是一个期约，则**会有两个任务被添加到消息队列**并被**异步求值**
  - **第一个任务**是等待期约的返回值，**第二个任务**是拿到返回值后执行进程
  - tc39 对`await`后面是期约的情况做过 1 次修改，`await Promise.resolve()`不再生成 2 个异步任务，而只是 1 个

```js
async function foo() {
  console.log(2)
  console.log(await Promise.resolve(8))
  console.log(9)
}

async function bar2() {
  console.log(4)
  console.log(await 6)
  console.log(7)
}

console.log(1)
foo()
console.log(3)
bar2()
console.log(5)
/*
  书本顺序：1 2 3 4 5 6 7 8 9
  浏览器顺序：1 2 3 4 5 8 9 6 7（tc39做过1次修改）
*/
```

## 异步函数策略

### 实现 sleep()

### 利用平行执行

### 串行执行期约

### 栈追踪与内存管理

## 总结 & 问点

- async 关键字的用法是什么？根据函数内返回值的不同，异步函数的返回值有哪些情况？
- await 关键字的用法是什么？根据等待值的不同，调用异步函数有哪些情况？其使用有哪些限制？
- JS 运行时遇到 await 关键字会怎样？函数的其余部分会在何时恢复执行？
